### ISSUE TITLE
Lip Sync for Blender 3.5

### ISSUE THREAD

**Issue by vladiR56** [Hunanbean/Papagayo-NGLipsyncImporterForBlender#3]
Hello. 
I'm a big fan of Papagayo. So I was happy because I found the Lip-SyncImporterBlender3_v1.py for Blender 3.5. I downloaded it. After that I want to install it in preferencies. Then this message came up: Modules Installed () from 'D:\\Projects\\Blender\\BLENDER_Add_ON\\Papagayo-NGLipsyncImporterForBlender-main.zip' into 'C:\\Users\\Vladi\\AppData\\Roaming\\ Blender Foundation\\Blender\\3.5\\scripts\\addons'
Unfortunately 

I can't find the Lipsync addon in Preferences to activate it. What I have done wrong? Can you please help me?

 Vladimir

**Comment by Hunanbean** [comment]
I should probably set up the Git better, now that there are multiple versions. Downloading the Zip itself will give you problems because of it. Here is a link to the Script directly.

[https://github.com/Hunanbean/Papagayo-NGLipsyncImporterForBlender/blob/main/Lip-SyncImporterBlender3_v1.py](https://github.com/Hunanbean/Papagayo-NGLipsyncImporterForBlender/blob/main/Lip-SyncImporterBlender3_v1.py)

![firefox_IiAEOEuUGN](https://github.com/Hunanbean/Papagayo-NGLipsyncImporterForBlender/assets/52123900/0530336a-1703-4b33-8caa-7e0285f5e173)

Now you can point Blender directly to the .py file and it will show up in the add-ons list.
Please let me know if there are any issues, thanks.

HB

**Comment by vladiR56** [comment]
Thanks. It works. Excellent.
Vladi
